# Generated by Django 5.0 on 2023-12-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название сайта ')),
                ('about_mission', models.TextField(verbose_name='описани миссии')),
                ('about_advates', models.TextField(verbose_name='описани преймушеста')),
                ('about_gorantes', models.TextField(verbose_name='описание горантие')),
                ('image', models.ImageField(upload_to='Картинка')),
            ],
            options={
                'verbose_name': 'Настройки о нас ',
                'verbose_name_plural': 'Настройка о нас',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_name', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='логотип')),
                ('mini_descriptions', models.CharField(max_length=255, verbose_name='слогон')),
                ('image', models.ImageField(upload_to='Картинка ')),
                ('we_creative', models.CharField(max_length=255, verbose_name='Название для 2 слайда')),
                ('mini_descriptions1', models.CharField(max_length=255, verbose_name='слогон')),
                ('image1', models.ImageField(upload_to='Картинка ')),
                ('we_best', models.CharField(max_length=255, verbose_name='Название 3 слайда ')),
                ('mini_descriptions2', models.CharField(max_length=255, verbose_name='слогон')),
                ('image2', models.ImageField(upload_to='Картинка')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройка',
            },
        ),
    ]
