# Generated by Django 5.0 on 2023-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='we_are',
            field=models.TextField(default=1, verbose_name='описание о компание'),
            preserve_default=False,
        ),
    ]
