# Generated by Django 5.0 on 2023-12-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about_we_are'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
