# Generated by Django 5.0 on 2023-12-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_delete_about_delete_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='we_name',
            new_name='name',
        ),
    ]
