# Generated by Django 5.0 on 2023-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
