# Generated by Django 5.0 on 2023-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name1',
            field=models.CharField(default=1, max_length=255, verbose_name='имя сотрудника(для нашей коммандой)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name2',
            field=models.CharField(default=1, max_length=255, verbose_name='имя сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name3',
            field=models.CharField(default=1, max_length=255, verbose_name='имя сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name4',
            field=models.CharField(default=1, max_length=255, verbose_name='имя сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='rols1',
            field=models.CharField(default=1, max_length=255, verbose_name='роль сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='rols2',
            field=models.CharField(default=1, max_length=255, verbose_name='роль сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='rols3',
            field=models.CharField(default=1, max_length=255, verbose_name='роль сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='rols4',
            field=models.CharField(default=1, max_length=255, verbose_name='роль сотрудника'),
            preserve_default=False,
        ),
    ]
