# Generated by Django 5.0 on 2023-12-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_employee_name1_employee_name2_employee_name3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo1',
            field=models.ImageField(default=1, upload_to='photo1', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo2',
            field=models.ImageField(default=1, upload_to='photo2', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo3',
            field=models.ImageField(default=1, upload_to='photo3', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='photo4',
            field=models.ImageField(default=1, upload_to='photo4', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
