# Generated by Django 5.0 on 2023-12-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'слайд', 'verbose_name_plural': 'слайды'},
        ),
    ]
