# Generated by Django 5.0 on 2023-12-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='clints',
            field=models.CharField(default=1, max_length=255, verbose_name='количества офисей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='hours_work',
            field=models.CharField(default=12, max_length=255, verbose_name='количкества рабочих часов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='ofise',
            field=models.CharField(default=1, max_length=255, verbose_name='количкества офисов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='project',
            field=models.CharField(default=1, max_length=255, verbose_name='количкества сделаных проектов'),
            preserve_default=False,
        ),
    ]
