# Generated by Django 5.0 on 2023-12-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_rename_ofise_settings_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='clints',
            field=models.CharField(max_length=255, verbose_name='количества клиетов'),
        ),
    ]
