# Generated by Django 5.0 on 2023-12-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_alter_settings_clints'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='video',
            field=models.URLField(default=1, verbose_name='промо ролик'),
            preserve_default=False,
        ),
    ]
