# Generated by Django 5.0 on 2023-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_settings_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='название проэкта')),
                ('image', models.ImageField(upload_to='proj_photo', verbose_name='фото проэкта')),
                ('disk', models.TextField(verbose_name='описание проекта')),
            ],
            options={
                'verbose_name': 'проэкт',
                'verbose_name_plural': 'проэкты',
            },
        ),
    ]
